project_name: prq
builds:
  - main: ./cmd/prq
    binary: prq
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
release:
  draft: true
brews:
  - name: prq
    tap:
      owner: YOUR_GITHUB_ORG
      name: homebrew-tap
    folder: Formula
scoops:
  - name: prq
    bucket:
      owner: YOUR_GITHUB_ORG
      name: scoop-bucket
